---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mariadb-operator
spec:
  interval: 1h
  path: ./kubernetes/apps/databases/mariadb/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: databases
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mariadb-cluster
spec:
  dependsOn:
    - name: mariadb-operator
    - name: rook-ceph-cluster
      namespace: rook-ceph
  healthCheckExprs:
    - apiVersion: k8s.mariadb.com/v1alpha1
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      kind: MariaDB
  interval: 1h
  path: ./kubernetes/apps/databases/mariadb/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: databases
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mariadb-tools
spec:
  dependsOn:
    - name: mariadb-operator
  interval: 1h
  path: ./kubernetes/apps/databases/mariadb/tools
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: databases
