[env]
KUBECONFIG = "{{config_root}}/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
OP_ACCOUNT = "woodleigh-school.1password.com"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/talosconfig"
JUST_UNSTABLE = "1"
LEFTHOOK_OUTPUT = "false"
CA_CERT_PATH = "/opt/homebrew/etc/ca-certificates/cert.pem"

_.file = [
  "{{config_root}}/.secrets.env",
]

[tools]
"aqua:helm/helm" = "4.0.5"
"uv" = "latest"
"pipx:flux-local" = "latest"
