---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adoverseas
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: adoverseas-secret
    template:
      data:
        API_KEY: "{{ .API_KEY }}"
        DATABASE_HOST: "{{ .DATABASE_HOST }}"
        DATABASE_NAME: "{{ .DATABASE_NAME }}"
        DATABASE_USER: "{{ .DATABASE_USER }}"
        DATABASE_PASSWORD: "{{ .DATABASE_PASSWORD }}"
        STAFF_DEPARTMENT: "{{ .STAFF_DEPARTMENT }}"
        AD_HOST: "{{ .AD_HOST }}"
        AD_BASE: "{{ .AD_BASE }}"
        AD_ADMIN_DN: "{{ .AD_ADMIN_DN }}"
        AD_ADMIN_PASSWORD: "{{ .AD_ADMIN_PASSWORD }}"
        AWAY_GROUPS: "{{ .AWAY_GROUPS }}"
        HOME_GROUPS: "{{ .HOME_GROUPS }}"
        MFA_GROUPS: "{{ .MFA_GROUPS }}"
        ADMIN_OIDC_ISSUER: "{{ .ADMIN_OIDC_ISSUER }}"
        ADMIN_OIDC_CLIENT_ID: "{{ .ADMIN_OIDC_CLIENT_ID }}"
        ADMIN_OIDC_CLIENT_SECRET: "{{ .ADMIN_OIDC_CLIENT_SECRET }}"
        SESSION_SECRET: "{{ .SESSION_SECRET }}"
        INITIAL_ADMIN_PASSWORD: "{{ .INITIAL_ADMIN_PASSWORD }}"
        SITE_BASE_URL: "{{ .SITE_BASE_URL }}"
        GRAPH_TENANT_ID: "{{ .GRAPH_TENANT_ID }}"
        GRAPH_CLIENT_ID: "{{ .GRAPH_CLIENT_ID }}"
        GRAPH_CLIENT_SECRET: "{{ .GRAPH_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: adoverseas