---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: snipe-it
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: snipe-it-secret
    template:
      data:
        APP_KEY: "{{ .APP_KEY }}"
        DB_CONNECTION: mysql
        DB_DATABASE: snipe-it
        DB_HOST: mariadb-primary.databases.svc.cluster.local
        DB_PASSWORD: "{{ .DB_PASSWORD }}"
        DB_USERNAME: "{{ .DB_USERNAME }}"
  dataFrom:
    - extract:
        key: snipe-it
