---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grinch
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grinch-secret
    template:
      data:
        ADMIN_OIDC_CLIENT_ID: "{{ .AZURE_CLIENT_ID }}"
        ADMIN_OIDC_CLIENT_SECRET: "{{ .AZURE_CLIENT_SECRET }}"
        ADMIN_OIDC_ISSUER: "https://login.microsoftonline.com/{{ .AZURE_TENANT_ID }}/v2.0"
        DATABASE_HOST: postgres-rw.databases.svc.cluster.local
        DATABASE_NAME: grinch
        DATABASE_PASSWORD: "{{ .DATABASE_PASSWORD }}"
        DATABASE_PORT: "5432"
        DATABASE_USER: "{{ .DATABASE_USER }}"
        GRAPH_CLIENT_ID: "{{ .AZURE_CLIENT_ID }}"
        GRAPH_CLIENT_SECRET: "{{ .AZURE_CLIENT_SECRET }}"
        GRAPH_TENANT_ID: "{{ .AZURE_TENANT_ID }}"
        INITIAL_ADMIN_PASSWORD: "{{ .INITIAL_ADMIN_PASSWORD }}"
        SESSION_SECRET: "{{ .SESSION_COOKIE_SECRET }}"
  dataFrom:
    - extract:
        key: grinch
