---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grinch
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grinch-secret
    template:
      data:
        ADMIN_PASSWORD: "{{ .INITIAL_ADMIN_PASSWORD }}"
        AUTH_SECRET: "{{ .SESSION_COOKIE_SECRET }}"
        DB_HOST: postgres-rw.databases.svc.cluster.local
        DB_NAME: grinch
        DB_PASSWORD: "{{ .DATABASE_PASSWORD }}"
        DB_USER: "{{ .DATABASE_USER }}"
        ENTRA_CLIENT_ID: "{{ .AZURE_CLIENT_ID }}"
        ENTRA_CLIENT_SECRET: "{{ .AZURE_CLIENT_SECRET }}"
        ENTRA_TENANT_ID: "{{ .AZURE_TENANT_ID }}"
        MICROSOFT_CLIENT_ID: "{{ .AZURE_CLIENT_ID }}"
        MICROSOFT_CLIENT_SECRET: "{{ .AZURE_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: grinch
